manifest:
  defaults:
    revision: v0.1 # version to use for this module and for ZMK
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: xudongz
      url-base: https://github.com/xudongzheng
    - name: urob
      url-base: https://github.com/urob
    - name: zephyr35
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
#      remote: zmkfirmware
#      revision: fix-battery-reporting
#      revision: custom-wq-pr
#      revision: main
      # remote: zephyr35
      # revision: core/zephyr-3.5-update
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-adaptive-key
      remote: urob
  self:
    path: config